### ISSUE TITLE
[Bug] Rosbridge service unsubscribes from data_request topic when using 'preview: true'

### ISSUE THREAD

**Issue by a13zen** [aws-samples/amazon-eks-autonomous-driving-data-service#40]
When using the rosbridge service to accept requests on the data_request topic, if the flag `preview: true` is set in the request, the pod with the rosbridge service unsubscribed to the data_request topic after sending the first step response. 

This causes the rosbridge service to not accept new requests

**Comment by ajayvohra2005** [comment]
This issue is not reproducible.
