### ISSUE TITLE
[Feature Request] Add flag to retain generated rosbag files

### ISSUE THREAD

**Issue by a13zen** [aws-samples/amazon-eks-autonomous-driving-data-service#41]
In some workflows, the files generated are not consumed or want to be played multiple times (potentially in a loop). Currently, the data client deletes the files after playing it in order to reduce costs of fsx/s3.

Add a flag to the data client to support maintaining the file. 

Bonus: Allow setting s3 lifecycle rules to clean up objects after specified amount of time instead

**Comment by ajayvohra2005** [comment]
Hash commit 2262b3c94a62c137bb99dbf3811c215ec3e59b79 resolves this issue. Added two new request parameters: `no_delete` and `no_playback`. If `no_playback` is `true`, `no_delete` is automatically forced `true`. If `no_delete` is true, the generated `rosbag` files are not deleted. If `no_playback` is true, the `rosbag` file are not played.
