### ISSUE TITLE
[Documentation] Include architecture diagram 

### ISSUE THREAD

**Issue by a13zen** [aws-samples/amazon-eks-autonomous-driving-data-service#46]
Currently the architecture diagram for the @[amazon-eks-autonomous-driving-data-service](https://github.com/aws-samples/amazon-eks-autonomous-driving-data-service) is captured in https://aws.amazon.com/blogs/architecture/field-notes-building-a-data-service-for-autonomous-driving-systems-development-using-amazon-eks/ but not in the repo. 

- Link to the supporting field notes
- Add architecture diagram to notes

**Comment by ajayvohra2005** [comment]
Hash commit f2cd0a3c4fcf086f568f6eada46d7c96d3cdd9f5 adds architecture diagram.
